//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen_Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacen_Productos()
        {
            this.Linea_pedido_c = new HashSet<Linea_pedido_c>();
        }
    
        public int Id { get; set; }
        public int Almacen { get; set; }
        public int Articulo { get; set; }
        public string Lote { get; set; }
        public int Stock { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<System.DateTime> FechaFabricacion { get; set; }
        public Nullable<System.DateTime> FechaEnvasado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Almacenes Almacenes { get; set; }
        public virtual Articulos Articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Linea_pedido_c> Linea_pedido_c { get; set; }
    }
}
