//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen_Productos
    {
        public int Almacen { get; set; }
        public int Articulo { get; set; }
        public int Stock { get; set; }
        public int StockDisponible { get; set; }
        public int StockMin { get; set; }
        public int StockMax { get; set; }
    
        public virtual Almacenes Almacenes { get; set; }
        public virtual Articulos Articulos { get; set; }
    }
}
