//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.pedido_c = new HashSet<pedido_c>();
        }
    
        public int idCli { get; set; }
        public string Razon_Social { get; set; }
        public string NIF { get; set; }
        public string NIF_R { get; set; }
        public string Domicilio { get; set; }
        public string CP { get; set; }
        public string Poblacion { get; set; }
        public string Provincia { get; set; }
        public string Pais { get; set; }
        public System.DateTime Fecha_A { get; set; }
        public string Tipo { get; set; }
        public int Estado { get; set; }
        public string Telefono { get; set; }
        public string Mail { get; set; }
        public string Web { get; set; }
        public string Imagen { get; set; }
    
        public virtual estados estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_c> pedido_c { get; set; }
    }
}
