//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int Numero { get; set; }
        public int IdCliente { get; set; }
        public int IdEmpresa { get; set; }
        public int IdPedido { get; set; }
        public System.DateTime Fecha { get; set; }
        public int TipoPedido { get; set; }
        public int Forma_pago { get; set; }
        public Nullable<float> Total_bruto { get; set; }
        public Nullable<float> Dto { get; set; }
        public Nullable<float> Dpp { get; set; }
        public Nullable<float> Portes { get; set; }
        public Nullable<int> IVA { get; set; }
        public Nullable<float> Re { get; set; }
        public Nullable<float> Cuota_Re { get; set; }
        public Nullable<float> Total { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empresas Empresas { get; set; }
    }
}
