//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class linea_factura
    {
        public int Linea { get; set; }
        public int N_factura { get; set; }
        public int Articulo { get; set; }
        public int Cantidad { get; set; }
        public float Precio { get; set; }
        public float IVA { get; set; }
        public Nullable<float> Importe { get; set; }
    }
}
