//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<albaran> albaran { get; set; }
        public virtual DbSet<articulo> articulo { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<contacto> contacto { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<estado_ped> estado_ped { get; set; }
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<facturas> facturas { get; set; }
        public virtual DbSet<forma_pago> forma_pago { get; set; }
        public virtual DbSet<iva> iva { get; set; }
        public virtual DbSet<linea_factura> linea_factura { get; set; }
        public virtual DbSet<linea_pedido_c> linea_pedido_c { get; set; }
        public virtual DbSet<linea_pedido_p> linea_pedido_p { get; set; }
        public virtual DbSet<pedido_c> pedido_c { get; set; }
        public virtual DbSet<pedido_p> pedido_p { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tarifa> tarifa { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
