//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido_c
    {
        public int Num_ped { get; set; }
        public int idCliente { get; set; }
        public string Destino { get; set; }
        public int Estado { get; set; }
        public int Forma_pago { get; set; }
        public System.DateTime Fecha_A { get; set; }
        public float Total { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual EstadosPedido EstadosPedido { get; set; }
        public virtual FormaPago FormaPago { get; set; }
    }
}
