//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_p
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedido_p()
        {
            this.linea_pedido_p = new HashSet<linea_pedido_p>();
        }
    
        public int Num_ped { get; set; }
        public System.DateTime Fecha_A { get; set; }
        public string Total { get; set; }
        public string Tipo { get; set; }
        public int Estado { get; set; }
        public int Forma_pago { get; set; }
        public int idProv { get; set; }
    
        public virtual estado_ped estado_ped { get; set; }
        public virtual forma_pago forma_pago1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<linea_pedido_p> linea_pedido_p { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
