//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.Pedido_p = new HashSet<Pedido_p>();
        }
    
        public int IdProveedor { get; set; }
        public string RazonSocial { get; set; }
        public string NIF { get; set; }
        public string Domicilio { get; set; }
        public string CP { get; set; }
        public string Poblacion { get; set; }
        public string Provincia { get; set; }
        public string Pais { get; set; }
        public System.DateTime Fecha_A { get; set; }
        public int Estado { get; set; }
        public string Telefono { get; set; }
        public string Mail { get; set; }
        public string Nota { get; set; }
        public string Imagen { get; set; }
        public string NombreComercial { get; set; }
        public string Movil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_p> Pedido_p { get; set; }
        public virtual Estados Estados { get; set; }
    }
}
